using System.Collections.Generic;
using System.Text;

namespace LCBridgeOverlay
{
    /// <summary>
    /// Ручной перевод названий ивентов BrutalCompanyMinusExtraReborn на русский.
    /// BCMER-ивент возвращает из Name() внутренний идентификатор ("TurretsEverywhere",
    /// "OldBirds", "BerserkTurrets" ...) — это и есть заголовки секций в его конфиге
    /// (VanillaEvents.cfg / ModdedEvents.cfg). XUnity.AutoTranslator такие camelCase-строки
    /// перевести не мог (отсюда «нет перевода / неправильный»), поэтому переводим сами
    /// по словарю. Ключ — нормализованное имя (строчные буквы+цифры), так что и
    /// "TurretsEverywhere", и "Turrets Everywhere" попадут в одну запись.
    /// Неизвестное имя возвращаем как есть (и один раз пишем в лог, чтобы дополнить словарь).
    /// </summary>
    public static class EventTranslate
    {
        private static readonly HashSet<string> _loggedMiss = new HashSet<string>();

        public static string ToRu(string raw)
        {
            if (string.IsNullOrEmpty(raw)) return raw;
            string key = Norm(raw);
            if (key.Length == 0) return raw;
            if (Map.TryGetValue(key, out var ru)) return ru;
            if (_loggedMiss.Add(key))
                Plugin.Log?.LogInfo($"[event-ru] нет перевода для ивента \"{raw}\" (ключ: {key}) — показываю как есть.");
            return raw;
        }

        private static string Norm(string s)
        {
            var sb = new StringBuilder(s.Length);
            foreach (char c in s.ToLowerInvariant())
                if ((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9')) sb.Append(c);
            return sb.ToString();
        }

        private static readonly Dictionary<string, string> Map = new Dictionary<string, string>
        {
            // ---------- Vanilla ----------
            ["allweather"] = "Вся погода сразу",
            ["antibounty"] = "Награда снята",
            ["anticoilhead"] = "Анти-койлхед",
            ["arachnophobia"] = "Арахнофобия",
            ["baboonhorde"] = "Орда павианов",
            ["badproduce"] = "Гнилой урожай",
            ["bees"] = "Пчёлы",
            ["berserkturrets"] = "Турели в ярости",
            ["bigbonus"] = "Большой бонус",
            ["bigdelivery"] = "Большая доставка",
            ["birds"] = "Птицы",
            ["blackfriday"] = "Чёрная пятница",
            ["bonus"] = "Бонус",
            ["bounty"] = "Награда за голову",
            ["bracken"] = "Бракен",
            ["bughorde"] = "Орда жуков",
            ["butlers"] = "Дворецкие",
            ["cadaver"] = "Трупоцвет",
            ["catsanddogs"] = "Кошки и собаки",
            ["clock"] = "Часы",
            ["coilhead"] = "Койлхед",
            ["controlpad"] = "Пульт управления",
            ["cruiserfailure"] = "Поломка крейсера",
            ["dentures"] = "Вставная челюсть",
            ["dogs"] = "Слепые псы",
            ["doorcircuitfailure"] = "Сбой цепи дверей",
            ["doorfailure"] = "Поломка дверей",
            ["dooroverdriveev"] = "Двери вразнос",
            ["dustpans"] = "Совки",
            ["dweller"] = "Пещерный житель",
            ["earlyship"] = "Ранний отлёт",
            ["eastereggs"] = "Пасхалки",
            ["explodingitems"] = "Взрывающиеся предметы",
            ["facilityghost"] = "Призрак комплекса",
            ["flashlightsfailure"] = "Сбой фонарей",
            ["flowersnake"] = "Тюльпановая змейка",
            ["footballscrap"] = "Ценный мяч",
            ["forestgiant"] = "Лесной великан",
            ["fragileenemies"] = "Хрупкие враги",
            ["fullaccess"] = "Полный доступ",
            ["garbagelid"] = "Крышка мусорки",
            ["giantsoutside"] = "Великаны снаружи",
            ["gloomy"] = "Пасмурно",
            ["goldenbars"] = "Золотые слитки",
            ["goldenfacility"] = "Золотой комплекс",
            ["grabbablelandmines"] = "Переносные мины",
            ["grabbableturrets"] = "Переносные турели",
            ["heavyrain"] = "Ливень",
            ["hell"] = "Ад",
            ["higherscrapvalue"] = "Лут дороже",
            ["hoardingbugs"] = "Жуки-барахольщики",
            ["holidayseason"] = "Праздники",
            ["honk"] = "Гудок",
            ["insidebees"] = "Пчёлы внутри",
            ["ismetal"] = "Металлический день",
            ["itemchargerfailure"] = "Сбой зарядной станции",
            ["jester"] = "Шут",
            ["jetpackfailure"] = "Сбой джетпака",
            ["kamikaziebugs"] = "Жуки-камикадзе",
            ["kidnapperfox"] = "Лис-похититель",
            ["kiwibird"] = "Гигантский киви",
            ["landmines"] = "Мины",
            ["lateship"] = "Поздний отлёт",
            ["leaflessbrowntrees"] = "Голые бурые деревья",
            ["leaflesstrees"] = "Голые деревья",
            ["leverfailure"] = "Сбой рычага отлёта",
            ["littlegirl"] = "Девочка-призрак",
            ["lizard"] = "Спор-ящер",
            ["lockedentrance"] = "Запертый вход",
            ["locusts"] = "Саранча",
            ["manualcamerafailure"] = "Сбой камер",
            ["masked"] = "Маскед",
            ["maskitem"] = "Маска",
            ["metalswitch"] = "Металлический рубильник",
            ["meteors"] = "Метеоры",
            ["moreexits"] = "Больше выходов",
            ["morescrap"] = "Больше лута",
            ["nobaboons"] = "Без павианов",
            ["nobirds"] = "Без птиц",
            ["nobracken"] = "Без бракена",
            ["nobutlers"] = "Без дворецких",
            ["nocoilhead"] = "Без койлхедов",
            ["nodogs"] = "Без псов",
            ["noghosts"] = "Без призраков",
            ["nogiants"] = "Без великанов",
            ["nohoardingbugs"] = "Без жуков-барахольщиков",
            ["nojester"] = "Без шута",
            ["nolandmines"] = "Без мин",
            ["nolizards"] = "Без ящеров",
            ["nomasks"] = "Без масок",
            ["nonutcracker"] = "Без щелкунчиков",
            ["nooldbird"] = "Без старых птиц",
            ["noslimes"] = "Без слизней",
            ["nosnarefleas"] = "Без блох",
            ["nospiders"] = "Без пауков",
            ["nospiketraps"] = "Без шипов",
            ["nothing"] = "Ничего",
            ["nothumpers"] = "Без тамперов",
            ["notmetal"] = "Не металл",
            ["noturrets"] = "Без турелей",
            ["noworm"] = "Без червя",
            ["nutcracker"] = "Щелкунчик",
            ["nutslayer"] = "Щелкунчик-палач",
            ["nutslayersmore"] = "Щелкунчики-палачи",
            ["oldbirds"] = "Старые птицы (мехи)",
            ["outsidelandmines"] = "Мины снаружи",
            ["outsideturrets"] = "Турели снаружи",
            ["pickles"] = "Огурчики",
            ["plasticcup"] = "Пластиковый стаканчик",
            ["plentyoutsidescrap"] = "Много лута снаружи",
            ["puma"] = "Феиопар",
            ["raining"] = "Дождь",
            ["realityshift"] = "Сдвиг реальности",
            ["safeoutside"] = "Снаружи безопасно",
            ["scarceoutsidescrap"] = "Мало лута снаружи",
            ["scrapgalore"] = "Лут в изобилии",
            ["severedbits"] = "Расчленёнка",
            ["shipcorefailure"] = "Сбой ядра корабля",
            ["shiplightsfailure"] = "Сбой света корабля",
            ["shipmentfees"] = "Плата за доставку",
            ["sid"] = "SID",
            ["slimeinside"] = "Слизень внутри",
            ["slimes"] = "Слизни",
            ["smalldelivery"] = "Малая доставка",
            ["smallermap"] = "Карта поменьше",
            ["snarefleas"] = "Блохи-душители",
            ["spiders"] = "Пауки",
            ["spiketraps"] = "Шипы-ловушки",
            ["stingray"] = "Скат",
            ["strongenemies"] = "Сильные враги",
            ["sussypaintings"] = "Подозрительные картины",
            ["targetingfailureevent"] = "Сбой наведения",
            ["teleporterfailure"] = "Сбой телепорта",
            ["teleportertraps"] = "Ловушки-телепорты",
            ["teleportin"] = "Телепортация внутрь",
            ["terminalfailure"] = "Сбой терминала",
            ["thumpers"] = "Тамперы",
            ["timechaos"] = "Хаос времени",
            ["toiletpaper"] = "Туалетная бумага",
            ["train"] = "Поезд",
            ["transmutescrapbig"] = "Трансмутация лута (много)",
            ["transmutescrapsmall"] = "Трансмутация лута (мало)",
            ["trapsfailure"] = "Сбой ловушек",
            ["trees"] = "Деревья",
            ["turrets"] = "Турели",
            ["turretseverywhere"] = "Турели повсюду",
            ["veryearlyship"] = "Очень ранний отлёт",
            ["verylateship"] = "Очень поздний отлёт",
            ["walkiefailure"] = "Сбой рации",
            ["warzone"] = "Зона боевых действий",
            ["welcometothefactory"] = "Добро пожаловать на завод",
            ["worms"] = "Земляные левиафаны",
            ["zeddog"] = "Пёс-зомби",

            // ---------- Modded ----------
            ["allslayers"] = "Все палачи",
            ["baddice"] = "Дурные кости",
            ["baldi"] = "Балди",
            ["barbers"] = "Барберы",
            ["bellcrab"] = "Краб-звоночек",
            ["bertha"] = "Берта",
            ["bloodmoon"] = "Кровавая луна",
            ["cityofgold"] = "Золотой город",
            ["cleaners"] = "Чистильщики",
            ["critters"] = "Мелкие твари",
            ["dice"] = "Кости",
            ["football"] = "Футбол",
            ["forsaken"] = "Забытый",
            ["foxy"] = "Фокси",
            ["giantshowdown"] = "Битва великанов",
            ["hallowed"] = "Хэллоуин",
            ["heatwave"] = "Аномальная жара",
            ["herobrine"] = "Херобрин",
            ["hotbarhassle"] = "Свистопляска инвентаря",
            ["hotbarmania"] = "Мания инвентаря",
            ["hurricane"] = "Ураган",
            ["immortalsnail"] = "Бессмертная улитка",
            ["itsplaytime"] = "Playtime",
            ["leafboys"] = "Листовые парни",
            ["lighteaterenemy"] = "Пожиратель света",
            ["lockers"] = "Локеры",
            ["majoramoon"] = "Луна Majora",
            ["manstalker"] = "Преследователь",
            ["mantitoil"] = "Мантикоил с турелью",
            ["mantitoilslayer"] = "Мантикоил-палач",
            ["meltdown"] = "Расплавление реактора",
            ["meteorshower"] = "Метеоритный дождь",
            ["moaienemy"] = "Моаи",
            ["mobileturrets"] = "Мобильные турели",
            ["needycats"] = "Назойливые коты",
            ["nemo"] = "Немо",
            ["nofiend"] = "Без Изверга",
            ["noimmortalsnails"] = "Без улиток",
            ["nolockers"] = "Без локеров",
            ["nomantitoil"] = "Без мантитоила",
            ["nomantitoilslayer"] = "Без мантитоила-палача",
            ["nopeepers"] = "Без Пиперов",
            ["noshyguy"] = "Без Шайгая",
            ["noslayers"] = "Без палачей",
            ["notoilslayer"] = "Без тойл-палача",
            ["peepers"] = "Пиперы",
            ["phonesout"] = "Телефоны наружу",
            ["playtimebig"] = "Playtime (большой)",
            ["rollinggiants"] = "Катящиеся великаны",
            ["roomba"] = "Робот-пылесос",
            ["scp682"] = "SCP-682",
            ["scp939"] = "SCP-939",
            ["seamine"] = "Морская мина",
            ["shiba"] = "Сиба-ину",
            ["shockwavedrones"] = "Дроны с ударной волной",
            ["shrimp"] = "Креветка",
            ["shyguy"] = "Шайгай",
            ["sirenhead"] = "Сиреноголовый",
            ["skullenemy"] = "Череп",
            ["slenderman"] = "Слендермен",
            ["solarflare"] = "Солнечная вспышка",
            ["souldev"] = "Souldev",
            ["takeygokubracken"] = "Бракен-Гоку",
            ["thefiend"] = "Изверг",
            ["toilhead"] = "Тойлхед (койл с турелью)",
            ["toilslayer"] = "Тойл-палач",
            ["walkers"] = "Ходоки",
            ["welcometoooblterra"] = "Добро пожаловать в Ooblterra",
            ["windy"] = "Ветрено",
            ["yeetbomb"] = "Бомба-йит",
        };
    }
}
